// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static bool get isConfiguredForCurrentPlatform {
    if (kIsWeb) return false;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android || TargetPlatform.iOS => true,
      _ => false,
    };
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZNY9dAIR9THzjpRaNFvPL4OzJ6wn3TE4',
    appId: '1:241322582096:android:dcf88078471e59c647b155',
    messagingSenderId: '241322582096',
    projectId: 'captioncraft-b1abb',
    storageBucket: 'captioncraft-b1abb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs1JR48M3K93Ct9aG3689rc5BvddsRQZg',
    appId: '1:241322582096:ios:b99e70b8fe2b2b4547b155',
    messagingSenderId: '241322582096',
    projectId: 'captioncraft-b1abb',
    storageBucket: 'captioncraft-b1abb.firebasestorage.app',
    androidClientId:
        '241322582096-f7fpfvuu9nuddoa0pq0n03u3av500e7n.apps.googleusercontent.com',
    iosClientId:
        '241322582096-gj0gd8aha12bcrpf7ltvk7e2dv21cvat.apps.googleusercontent.com',
    iosBundleId: 'com.captioncraft.captionCraft',
  );
}
